#!/bin/bash
# Renders the files that are generated from emulators.json.
#
#   scripts/render.sh          rewrite the generated files
#   scripts/render.sh --check  exit 1 if any generated file is out of date
#
# Requires jq.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
config="$root/emulators.json"
check=0
[[ "${1:-}" == "--check" ]] && check=1

"$root/scripts/validate.sh"

compose() {
	local image
	image="$(jq -r '"\(.namespace)/\(.repository)"' "$config")"
	cat <<EOF
# Generated by scripts/render.sh from emulators.json. Do not edit by hand.
#
# Headless emulator farm. One container per API, run from the prebuilt images
# on Docker Hub (pulled on first use). Host adb port is 5000+API, bound to
# 127.0.0.1. Requires /dev/kvm on the host.
#
#   docker compose up -d api36
#   IMAGE=other/android-emulator-farm docker compose up -d api36

x-emulator: &emulator
  pull_policy: missing
  devices:
    - /dev/kvm:/dev/kvm
  shm_size: "2gb"
  restart: "no"
  environment:
    BOOT_TIMEOUT: \${BOOT_TIMEOUT:-600}
    EMULATOR_MEMORY: \${EMULATOR_MEMORY:-}
    EMULATOR_CORES: \${EMULATOR_CORES:-}
    EMULATOR_ARGS: \${EMULATOR_ARGS:-}

services:
EOF
	jq -r --arg image "$image" '.emulators[] |
		"  # API \(.api) (Android \(.android), \(.system_image)) — adb 127.0.0.1:\(5000 + (.api|tonumber))",
		"  api\(.api):",
		"    <<: *emulator",
		"    image: ${IMAGE:-\($image)}:api\(.api)",
		"    container_name: emulator-farm-\(.api)",
		"    ports:",
		"      - \"127.0.0.1:\(5000 + (.api|tonumber)):5556\""' "$config"
}

# Markdown table of APIs and tags, shared by README.md and docs/dockerhub.md.
table() {
	echo '| API | Android | System image | Tags | Host adb |'
	echo '|---|---|---|---|---|'
	jq -r '.latest as $latest | .emulators[] |
		([ "api\(.api)", .api, "android-\(.android)", "api\(.api)-\(.system_image)" ]
			+ (if .api == $latest then ["latest"] else [] end)
			| map("`\(.)`") | join(", ")) as $tags
		| "| \(.api) | \(.android) | `\(.system_image)` | \($tags) | `127.0.0.1:\(5000 + (.api|tonumber))` |"' "$config"
}

# Prints $1 with the lines between the emulators markers replaced by stdin.
splice() {
	local file="$1" body
	body="$(cat)"
	grep -q '^<!-- emulators:start -->$' "$file" || { echo "$file has no emulators markers" >&2; return 1; }
	awk -v body="$body" '
		/^<!-- emulators:start -->$/ { print; print body; skip = 1; next }
		/^<!-- emulators:end -->$/ { skip = 0 }
		!skip' "$file"
}

# Writes stdin to $1, or compares in --check mode.
emit() {
	local target="$1" tmp
	tmp="$(mktemp)"
	cat >"$tmp"
	if ((check)); then
		if ! diff -u "$root/$target" "$tmp"; then
			rm -f "$tmp"
			echo "$target is out of date. Run: make render" >&2
			return 1
		fi
		rm -f "$tmp"
	else
		cat "$tmp" >"$root/$target"
		rm -f "$tmp"
		echo "rendered $target"
	fi
}

status=0
compose | emit docker-compose.yml || status=1
for doc in README.md docs/dockerhub.md; do
	if grep -q '^<!-- emulators:start -->$' "$root/$doc"; then
		table | splice "$root/$doc" | emit "$doc" || status=1
	fi
done
exit "$status"
