#!/bin/bash
# Renders the files that are generated from emulators.json.
#
#   scripts/render.sh          rewrite the generated files
#   scripts/render.sh --check  exit 1 if any generated file is out of date
#
# Requires jq.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
config="$root/emulators.json"
check=0
[[ "${1:-}" == "--check" ]] && check=1

"$root/scripts/validate.sh"

compose() {
	cat <<'EOF'
# Generated by scripts/render.sh from emulators.json. Do not edit by hand.
#
# Headless emulator farm. One container per API. Host adb port is 5000+API,
# bound to 127.0.0.1. Requires /dev/kvm on the host.
#
# IMAGE is the repository, without a tag. The default builds local images.
#   IMAGE=namespace/android-emulator-farm make run API=36

x-build: &build
  context: ./docker
  target: emulator

x-emulator: &emulator
  privileged: true
  shm_size: "2gb"
  restart: "no"
  environment:
    BOOT_TIMEOUT: ${BOOT_TIMEOUT:-600}
    EMULATOR_MEMORY: ${EMULATOR_MEMORY:-}
    EMULATOR_CORES: ${EMULATOR_CORES:-}
    EMULATOR_ARGS: ${EMULATOR_ARGS:-}

services:
EOF
	jq -r '.emulators[] |
		"  # API \(.api) (Android \(.android), \(.system_image)) — adb 127.0.0.1:\(5000 + (.api|tonumber))",
		"  api\(.api):",
		"    <<: *emulator",
		"    image: ${IMAGE:-android-emulator-farm}:api\(.api)",
		"    container_name: emulator-farm-\(.api)",
		"    build:",
		"      <<: *build",
		"      args:",
		"        API: \"\(.api)\"",
		"        SYSTEM_IMAGE: \(.system_image)",
		"    ports:",
		"      - \"127.0.0.1:\(5000 + (.api|tonumber)):5556\""' "$config"
}

# Writes stdin to $1, or compares in --check mode.
emit() {
	local target="$1" tmp
	tmp="$(mktemp)"
	cat >"$tmp"
	if ((check)); then
		if ! diff -u "$root/$target" "$tmp"; then
			rm -f "$tmp"
			echo "$target is out of date. Run: make render" >&2
			return 1
		fi
		rm -f "$tmp"
	else
		mv "$tmp" "$root/$target"
		echo "rendered $target"
	fi
}

status=0
compose | emit docker-compose.yml || status=1
exit "$status"
